### ISSUE TITLE
As a user, I need to be able to pick a username that isn't already taken

### ISSUE THREAD

**Issue by mikepif** [newjersey/dhs-oneapp#101]
### Description or User Story

The account creation page requires a username, so to enable account creation we need to be able to check if a username provided by the user is not already taken.

### Frontend Tasks (to be completed by Dev)

- [ ] Username input field with validation state based on availability of username

### Backend Tasks (to be completed by Dev)

- [x] GraphQL end point for querying user by username, and should not return any user info other than the username or true/false if the username is taken. Also should not require authentication.

### Acceptance Criteria

- [ ] Validation state reflects database values
- [ ] Route does not return any user info
- [ ] Route returns true for a pre-existing username
- [ ] Username is case insensitive

**Comment by ronaldheft-usds** [comment]
@Samara-Strauss Why is this ticket in the icebox? I think we're doing active dev on this. Back-end has support for username lookup.

**Comment by Samara-Strauss** [comment]
I'm not sure. I haven't seen this ticket before.

I've moved this to In Progress.

**Comment by ronaldheft-usds** [comment]
@mikepif Are you handling updating this ticket? This should be done from the back-end perspective now.

**Comment by Samara-Strauss** [comment]
Wondering if this is done from a FE perspective as part of #24. @mikepif let us know if there is still work to be done here or if we can close this out.

**Comment by leahbannon2** [comment]
@mikepif to verify that this is done

**Comment by Samara-Strauss** [comment]
Initial work was done, but there was a bug found that needs to be resolved before we can close this out.
