### ISSUE TITLE
[PM] Move notes to wiki

### ISSUE THREAD

**Issue by leahbannon2** [newjersey/dhs-oneapp#103]
Some documents would likely be more usable if they were browsable in a wiki than in md documents: 
- meeting notes
- [strategy "plan"](https://github.com/newjersey/dhs-oneapp/tree/main/plan)
- [decision documents](https://github.com/newjersey/dhs-oneapp/tree/main/decisions)
- before/after and decisions spreadsheet

Organize (when possible) by application sections, similar to spreadsheet.

Review
- [x] background info
- [x] build_one_requirements
- [x] design
- [x] dhs
- [x] flow-diagrams
- [x] furloughs
- [x] images
- [x] meeting-notes
- [x] one-app-datapoints
- [x] one_app/paper_apps
- [x] oneapp-demo
- [x] plan-strategy
- [x] research
- [x] technical_specs
- [x] testing
- [x] weekly-summary

**Comment by Samara-Strauss** [comment]
- Blocked. Waiting on IA spreadsheet. Also, the IA spreadsheet might make this obsolete.

**Comment by Samara-Strauss** [comment]
Moving to week of 9/22
