### ISSUE TITLE
[FE/BE] GraphQL: Backend/frontend strategy

### ISSUE THREAD

**Issue by Samara-Strauss** [newjersey/dhs-oneapp#129]
## Background

In our 8.27.20 meeting, Ron mentioned he wanted to create some documentation around the most important pieces of data for the frontend so that he can prioritize his work and prevent any blockers for Mike on the frontend.

This ticket is to make a priority plan for what the frontend needs from the backend so that if there is anything the frontend needs more immediately, Mike has what he needs.

## Tasks

- [x] Mike and Ron regroup to figure out the strategy going forward
- [x] If necessary, create a list of priorities for the frontend

**Comment by Samara-Strauss** [comment]
Next steps: @ronaldheft-usds will regroup with @mikepif for a conversation on how to move this forward

**Comment by ronaldheft-usds** [comment]
Documented here: https://github.com/newjersey/dhs-oneapp/blob/main/development/Stored_Procedures.md

Still need to meet with @mikepif

**Comment by Samara-Strauss** [comment]
Ron and Mike will meet later this week to discuss.

**Comment by ronaldheft-usds** [comment]
Met today. @mikepif and I discussed:

* Back-end will return standard error messages for all errors, include translation codes.
* Back-end will provide endpoint for returning all translation values; front-end to leverage this endpoint to look up translation messages.
* Front-end to send locale code to all back-end endpoints via header. Will be used by back-end for translation endpoint and any stored procedures that require locale code.

**Comment by ronaldheft-usds** [comment]
Talked through the work that needs to be done between front-end and back-end. Created additional tickets to track new work. We are able to close out this ticket.

**Comment by Samara-Strauss** [comment]
Awesome! Thanks for letting me know.
