### ISSUE TITLE
[PM] IA mapping: Resolve some of the existing InVision comments with NJ team

### ISSUE THREAD

**Issue by Samara-Strauss** [newjersey/dhs-oneapp#153]
## Background

Epic #143

Melissa has undertaken the huge task of mapping the existing IA of OneApp, the new structure we are proposing, and how these two versions map to each other. 

As part of this, Leah has offered to help get resolution on some of the questions/comments that had been left in the InVision prototype. This may help answer some of the IA-related questions/issues that we/NJ have to help Melissa move along this work.

## Tasks

- [ ] Week of 9/8: Resolve as many InVision comments with NJ team as possible

**Comment by leahbannon2** [comment]
Closing this in favor of #250
