### ISSUE TITLE
[FE] Application sign up: Design review/validation

### ISSUE THREAD

**Issue by Samara-Strauss** [newjersey/dhs-oneapp#155]
## Background

Mike completed the initial frontend build for the application sign up page in #24. However, because we don't yet have the staging environment up, and because Melissa is currently out on the RI sprint, design review/validation of Mike's build was unable to happen. This ticket is for making sure that review happens once staging is ready and Melissa is back.

## Tasks

- [ ] Review the application sign up page with Melissa in staging
- [ ] If necessary, make adjustments/fixes based on her feedback

Review: 
- Review content to see if it's correct
  - Mobile versus desktop design content
- Typography
- Pixel perfect match?
- Responsiveness

**Comment by allyceh** [comment]
Assigning myself since this is part of the MVP and will likely be included in the design chat with @mikepif

**Comment by allyceh** [comment]
@mikepif @leahbannon2 Doing some housekeeping. Closing this, combining with 120. Mike and I talked about it making more sense.
