### ISSUE TITLE
[BE] An API end-point for getting and updating the language config

### ISSUE THREAD

**Issue by mikepif** [newjersey/dhs-oneapp#173]
The client needs a API end point to get all the language mappings for the app, and also an end-point for update the list.

The data structure is pretty open, the client currently uses a data structure like - but we should discuss for sure;

`    const messages = {
        en: {
            home_0: 'Apply for New Jersey social services',
            home_1: 'Already started an application?',
            home_2: 'Sign In',
            home_3: 'Get food or cash assistance through one application',
            login_1: 'Password must be 8 to 15 characters long, contain at least one letter and one number. No special characters or spaces are allowed.'
        },
        es: {
            home_0: 'Solicitar servicios sociales de Nueva Jersey',
            home_1: '¿Ya comenzó una aplicación?',
            home_2: 'Iniciar sesión',
            home_3: 'Obtenga asistencia alimentaria o en efectivo a través de una solicitud.',
            login_1: 'La contraseña debe tener de 8 a 15 caracteres, contener al menos una letra y un número. No se permiten caracteres especiales ni espacios.'
        }
    };`

**Comment by ronaldheft-usds** [comment]
Kicked off development on this. Will take 1-2 days.

**Comment by ronaldheft-usds** [comment]
Done. Included in PR #205. Holding on merge for #206.

@mikepif Do we actually need endpoints for updating the language config? Are you building a UI for that? I would think it's going to be easier to update the values directly in the database with SQLDeveloper.
