### ISSUE TITLE
Migrate staging environment to USDS's cloud.gov account

### ISSUE THREAD

**Issue by ronaldheft-usds** [newjersey/dhs-oneapp#181]
### Description or User Story

The OneApp staging account is current in a trial cloud.gov account under Ron Heft's account. It will need to be refreshed every 30 days.

This ticket covers moving the staging account to the USDS account.

Waiting on Lisa to free up resources in USDS account.

### Backend Tasks (to be completed by Dev)

- [x] Change deployment target to USDS's account
- [ ] Notify team of new staging URL

### Acceptance Criteria

- [x] Staging environment is in USDS cloud.gov account
- [x] 256MB of memory is reserved in the USDS account for our staging environment

**Comment by ronaldheft-usds** [comment]
Parameterize the cloud.gov config, so it's easier to change accounts. https://github.com/newjersey/dhs-oneapp/commit/09d77192b3e94e7298c0022b2219e1f236ef7a9e

**Comment by Samara-Strauss** [comment]
Ron still needs to follow up with Lisa. Hopefully resources in cloud.gov have freed up so we can deploy out.
