### ISSUE TITLE
Back-end and front-end passes a standard language header code

### ISSUE THREAD

**Issue by ronaldheft-usds** [newjersey/dhs-oneapp#185]
### Description or User Story

A standard language locale header will be added to all back-end API calls. The back-end will assume English if this header is omitted or invalid.

### Frontend Tasks (to be completed by Dev)

- [ ] Captured in #193

### Backend Tasks (to be completed by Dev)

- [x] Define header and expected values
- [x] Update endpoints to use header value

### Acceptance Criteria

- [x] Back-end receives locale code from front-end
- [x] English is used as the default

**Comment by ronaldheft-usds** [comment]
Done. Included in PR #205. Holding on merge for #206.

**Comment by Samara-Strauss** [comment]
Ready to close. FE work is in #193.
