### ISSUE TITLE
[BE] Create endpoint for resetting a password after a user confirms their hint question

### ISSUE THREAD

**Issue by Samara-Strauss** [newjersey/dhs-oneapp#189]
## Background

In 9.22.20 planning, Ron mentioned we still need an endpoint for resetting a password after a user confirms their hint question. Adding this ticket to track that work.

## Tasks

- [ ] Create endpoint for resetting a password after a user confirms their hint question.

**Comment by Samara-Strauss** [comment]
@ronaldheft-usds did you still want this to be part of this week, or should we include this for next week in order to prioritize the work that needs to be done on mapping required questions?

**Comment by ronaldheft-usds** [comment]
This will probably slip to next week, but I'll have a better idea by EOD as to how long the required field work will take.

**Comment by Samara-Strauss** [comment]
Sounds good. Thanks for the update!
