### ISSUE TITLE
Document Windows installation directions for NJ DHS team and get them up and running

### ISSUE THREAD

**Issue by ronaldheft-usds** [newjersey/dhs-oneapp#207]
Carmen has requested we document out all of the steps for installing and running the new version of OneApp on a Windows machine.

**Comment by ronaldheft-usds** [comment]
NJ is having issues installing the Oracle dependency, as their firewall is blocking downloads. We are working on finding alternative install directions.

**Comment by ronaldheft-usds** [comment]
Windows setup directions are available here, but this does not yet include directions for getting around the firewall: https://github.com/newjersey/dhs-oneapp/blob/main/development/Windows_Setup.md

**Comment by leahbannon2** [comment]
Everyone has a working environment!
