### ISSUE TITLE
Plan out the quick submit technical work

### ISSUE THREAD

**Issue by ronaldheft-usds** [newjersey/dhs-oneapp#226]
- [x] Determine how to run quick submit in staging environment
- [ ] Identify which form fields need to be filled out for flow (this will require assistance from design)
- [ ] Identify which stored procedures need to be called
- [ ] Create tickets for quick submit work

**Comment by Samara-Strauss** [comment]
Blocked until we get further guidance from design on Quick Submit requirements.

**Comment by ronaldheft-usds** [comment]
Meeting schedule for Monday to review findings with @mayaisrani and @mikepif .
