### ISSUE TITLE
[FE] Application sign up

### ISSUE THREAD

**Issue by melissajschaff** [newjersey/dhs-oneapp#24]
### Description or User Story
As a user I want to start an application by creating an account.

### Screenshots
https://dhs.invisionapp.com/d/main#/console/20094964/425126493/preview

 - [Desktop version](https://dhs.invisionapp.com/d/main#/console/20094964/425126493/preview)

- [Mobile version](https://dhs.invisionapp.com/d/main#/console/20143160/422308919/pre![Application_Signup@2x.png](https://images.zenhubusercontent.com/59ca9059b0222d5de4793599/1282e00c-a9ab-4ab8-b2c8-938f1c1e23cc)view)![Application_Signup@2x (1).png](https://images.zenhubusercontent.com/59ca9059b0222d5de4793599/24babede-5eef-41f1-bd3f-68b46320006c)

### Acceptance Criteria

- [ ] Form built out on desktop
- [ ] Form is responsive and works for smaller viewports (tablet, mobile)
- [ ] Field validation works correctly (vaidation rules/design/copy)
- [ ] All preliminary copy is entered as shown in the mockup (we will create new tickets for future copy changes)
- [ ] All buttons/links go to correct location

Spanish translation will be tracked in another ticket.

**Comment by Samara-Strauss** [comment]
Closing. Initial build is done, needs additional tickets for review by Melissa once the staging environment is up and Melissa is back.
