### ISSUE TITLE
Continue onboarding guide

### ISSUE THREAD

**Issue by allyceh** [newjersey/dhs-oneapp#248]
- [x] Make list of resources that have helped me as a new person, currently lives in Slack

**Comment by Samara-Strauss** [comment]
Leah and Allyce to regroup on what kind of documentation is helpful.

**Comment by allyceh** [comment]
@mikepif @leahbannon2 @melissajschaff @bestes-usds @ronaldheft-usds I took an initial pass at an onboarding guide that lives as a pinned post in our Slack channel. The goal is to provide new team members with a few resources that will give them a good lay of the land. 

Can you all review, and add anything you think is missing?
