### ISSUE TITLE
[FE] Forgot username

### ISSUE THREAD

**Issue by melissajschaff** [newjersey/dhs-oneapp#26]
### Description or User Story
As a user with an account, I need to have my username sent to me because I forgot it. 

### Screenshots

 - [Desktop version](https://dhs.invisionapp.com/d/main#/console/20094964/421673558/preview)![Application_Username@2x.png](https://images.zenhubusercontent.com/59ca9059b0222d5de4793599/7bd6f998-943a-48a1-8836-db363ac42702)

-  Mobile version

### Acceptance Criteria

- [ ] Form built out on desktop
- [ ] Form is responsive and works for smaller viewports (tablet, mobile)
- [ ] Field validation works correctly (vaidation rules/design/copy)
- [ ] All preliminary copy is entered as shown in the mockup (we will create new tickets for future copy changes)
- [ ] All buttons/links go to correct location

**Comment by Samara-Strauss** [comment]
Needs API endpoints in order to complete build

**Comment by Samara-Strauss** [comment]
Still waiting on backend endpoint from Ron. Mike will push this to the end of the week. If endpoint is't ready, Mike can still build out UI.
