### ISSUE TITLE
Create a service blueprint to document how applicants and caseworkers use the current state application and systems

### ISSUE THREAD

**Issue by allyceh** [newjersey/dhs-oneapp#294]
Creating a service blueprint will allow us, NJ, and new team members to quickly see (from end-to-end) the process of applying for SNAP benefits. 

It will also help us answer questions (below) and understand the gaps that we have: 

- What happens after an applicant submits a quick submit application?
- etc
- etc

**Comment by leahbannon2** [comment]
[First draft posted here](https://github.com/usds/covid-19/blob/master/new-jersey/safety-net-benefits/design/journey-map.md)
