### ISSUE TITLE
[BE] Create app contact GraphQL query and mutation

### ISSUE THREAD

**Issue by ronaldheft-usds** [newjersey/dhs-oneapp#298]
Update the application type built in #297 to support the following GraphQL mutations:

* `OA_PKG_APP.SP_SELECT_APP_CONTACT`
* `OA_PKG_APP.SP_UPDATE_APP_CONTACT`

Ensure validations for the GraphQL type match validations found in:

* `/Forms/Application/Contact.aspx`

Acceptance criteria:

* The application query calls the `_SELECT_` stored procedure.
* The application mutation calls the `_UPDATE_` stored procedure.
* The GraphQL type has validations that enforce the rules defined in the legacy ASP pages.

**Comment by ronaldheft-usds** [comment]
@mayaisrani Would you be open to taking over this issue once we get the pattern for this issues set in your PR #368?

**Comment by mayaisrani** [comment]
happy to!
