### ISSUE TITLE
[BE] Create county and zipcode GraphQL queries and mutations

### ISSUE THREAD

**Issue by ronaldheft-usds** [newjersey/dhs-oneapp#304]
As part of creating a contact for the application, the zipcode must be validated to ensure it matches a zip code in NJ. There are additional stored procedures to return country information once the county is known from a zipcode.

Extend our GraphQL server to support the following stored procedures:

* `OA_PKG_APP.SP_VALIDATE_ZIPCODE`
* `OA_PKG_GEN.SP_GET_COUNTIES`
* `OA_PKG_GEN.SP_GET_COUNTY_DETAILS`

Ensure validations for the GraphQL type match validations found in:

* `/Forms/Application/Contact.aspx`

Acceptance criteria:

* The GraphQL type has validations that enforce the rules defined in the legacy ASP pages.

**Comment by mayaisrani** [comment]
existing functionality in https://github.com/newjersey/dhs-oneapp-legacy/blob/master/NJOneAppAuto/Forms/Application/Contact.aspx.cs#L134
