### ISSUE TITLE
[BE] Create USPS address validation GraphQL query

### ISSUE THREAD

**Issue by ronaldheft-usds** [newjersey/dhs-oneapp#305]
As part of validating addresses on `/Forms/Application/Contact.aspx`, the legacy version of OneApp calls a NJ maintained API to validate USPS addresses. We should expose that USPS validation API via the GraphQL server.

As most likely the API is locked down to the NJ network, we will need to create a mocked API for our local development and staging server.

- [ ] Verify if the USPS API is accessible outside of NJ's network
- [ ] Check with NJ if the API could be opened up to our staging server
- [ ] Build a mocked USPS API for local development
- [ ] Expose the API to the GraphQL server
- [ ] Match any data validations in `/Forms/Application/Contact.aspx`

**Comment by ronaldheft-usds** [comment]
Loaded up the USPS API from my NJ VM and made several discoveries.

1) There are actually quite a few methods in the WSDL, including a `getCloseMatchedAddresses` method. /cc @mikepif 

<img src="https://images.zenhubusercontent.com/5f3ac2dde53fec43bf1e475b/53804ee0-da19-468d-a459-6ef06c379215" width="300">

2) Unfortunately, OneApp is only authorized for the `getAddressDetails` method. Requesting any other method returns the following error:

```xml
<soap:Envelope
    xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
    <soap:Body>
        <validateAddressResponse
            xmlns="https://sws.dhs.state.nj.us">
            <validateAddressResult>APP_UNAUTHORIZED: application ONE-APP is not authorized to access this web method (ONE-APP -&gt; validateAddress)</validateAddressResult>
        </validateAddressResponse>
    </soap:Body>
</soap:Envelope>
```

3) The `getAddressDetails` method actually does function as a sanitizer. It's not returning simply true/false as we originally thought; it returns the full valid address. See the below example and notice how `Road` is changed to `Rd`.

Request:

```xml
<x:Envelope
    xmlns:x="http://schemas.xmlsoap.org/soap/envelope/"
    xmlns:sws="https://sws.dhs.state.nj.us">
    <x:Header/>
    <x:Body>
        <sws:getAddressDetails>
            <sws:address>2150 New Village Road</sws:address>
            <sws:CtyStateOrZip>08886</sws:CtyStateOrZip>
            <sws:accessKey>REMOVED</sws:accessKey>
        </sws:getAddressDetails>
    </x:Body>
</x:Envelope>
```

Response:
```xml
<soap:Envelope
    xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
    <soap:Body>
        <getAddressDetailsResponse
            xmlns="https://sws.dhs.state.nj.us">
            <getAddressDetailsResult>&lt;?xml version='1.0'?&gt;
&lt;usps&gt;
&lt;address1&gt;2150 NEW VILLAGE RD&lt;/address1&gt;
&lt;city&gt;STEWARTSVILLE&lt;/city&gt;
&lt;state&gt;NJ&lt;/state&gt;
&lt;zip&gt;08886&lt;/zip&gt;
&lt;zip4&gt;2664&lt;/zip4&gt;
&lt;countycode&gt;041&lt;/countycode&gt;
&lt;/usps&gt;</getAddressDetailsResult>
        </getAddressDetailsResponse>
    </soap:Body>
</soap:Envelope>
```

4) The API is also pretty flexible. The previous request can also be made with the city/state and some info omitted:

Request:

```xml
<x:Envelope
    xmlns:x="http://schemas.xmlsoap.org/soap/envelope/"
    xmlns:sws="https://sws.dhs.state.nj.us">
    <x:Header/>
    <x:Body>
        <sws:getAddressDetails>
            <sws:address>2150 New Village</sws:address>
            <sws:CtyStateOrZip>Stewartsville, NJ</sws:CtyStateOrZip>
            <sws:accessKey>REMOVED</sws:accessKey>
        </sws:getAddressDetails>
    </x:Body>
</x:Envelope>
```

Response:

```xml
<soap:Envelope
    xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
    <soap:Body>
        <getAddressDetailsResponse
            xmlns="https://sws.dhs.state.nj.us">
            <getAddressDetailsResult>&lt;?xml version='1.0'?&gt;
&lt;usps&gt;
&lt;address1&gt;2150 NEW VILLAGE RD&lt;/address1&gt;
&lt;city&gt;STEWARTSVILLE&lt;/city&gt;
&lt;state&gt;NJ&lt;/state&gt;
&lt;zip&gt;08886&lt;/zip&gt;
&lt;zip4&gt;2664&lt;/zip4&gt;
&lt;countycode&gt;041&lt;/countycode&gt;
&lt;/usps&gt;</getAddressDetailsResult>
        </getAddressDetailsResponse>
    </soap:Body>
</soap:Envelope>
```

5) When an address doesn't exist, or not enough information is provided, the response is simply an error.

Request:

```xml
<x:Envelope
    xmlns:x="http://schemas.xmlsoap.org/soap/envelope/"
    xmlns:sws="https://sws.dhs.state.nj.us">
    <x:Header/>
    <x:Body>
        <sws:getAddressDetails>
            <sws:address>2150 New Village</sws:address>
            <sws:CtyStateOrZip>Stewartsville</sws:CtyStateOrZip>
            <sws:accessKey>REMOVED</sws:accessKey>
        </sws:getAddressDetails>
    </x:Body>
</x:Envelope>
```

Response:

```xml
<soap:Envelope
    xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
    <soap:Body>
        <getAddressDetailsResponse
            xmlns="https://sws.dhs.state.nj.us">
            <getAddressDetailsResult>ERROR</getAddressDetailsResult>
        </getAddressDetailsResponse>
    </soap:Body>
</soap:Envelope>
```

@mayaisrani Let me know if you'd like me to capture any more requests. Looks like we will need to change up our API to return either an invalid response or the address as reported by USPS.

@mikepif Looks like we'll have to decide how we want the front-end to handle this. Will it replace the address with the correct address from USPS? Suggest the replacement? I'm thinking an automatic replacement is best, but how that's done I'm not sure. /cc @allyceh

**Comment by allyceh** [comment]
Looping in @melissajschaff as she is currently working on the wireframes. 

The most common scenario I've seen is that the application suggests the USPS replacement address, but allows the applicant to override the suggestion if they prefer. This is a poor example that I found on google... but it illustrates the functionality that I am referring to. 

<img width="611" alt="Screen Shot 2020-12-01 at 12 23 37 PM" src="https://user-images.githubusercontent.com/40216950/100774634-4643e180-33d0-11eb-9960-9d83e9ece9af.png">

Melissa, we'd have to think through this interaction if we go this route.

**Comment by melissajschaff** [comment]
@ronaldheft-usds @mikepif is there a specific geo API that NJ is already using? Or, do we need to recommend one?

**Comment by melissajschaff** [comment]
a few general questions relating back to this (to solve for post-MVP):
- what is the intent behind geo-checking? 
     - we don't have metrics and we _assume_ you can submit without a validated address
     - Melissa assumes that geo-checking is primarily for caseworkers, _not_ customers, meaning the intent is to determine county based on address (or search county if no address)
- would an alternative geo API be more suitable? 

I'd like to propose that for QS MVP we use the existing API, suggest to NJ that we set up analytics, and from there determine the efficacy of the existing geo API, or if we should look for an alternative.

Should it be determined that an alternative geo API be ideal, further investigate how it is useful to caseworkers and customers.
