### ISSUE TITLE
Improve readability of step-by-step page

### ISSUE THREAD

**Issue by bestes-usds** [newjersey/dhs-oneapp#396]
**Screenshot of quick submit screen**
![Screen Shot 2020-11-20 at 1.17.56 AM.png](https://images.zenhubusercontent.com/5f579fdff369d2367fddffb6/52ed17ef-0386-4106-9bef-7eb247e39963)

**Design principle**
- All content should be at a 5th grade reading level, which is readable and comprehensible for the greatest number of people.
- Measure reading level with tools like Hemingway editor and Readable.

**Recommendation**
- Hemingway finds the following sentences hard to read. Edits are provided:
  - "Depending on ~~the amount of people in your household and the amount of information you provide~~ [your situation], this should take about 15 to 45 minutes." Or "This should take about 15 to 45 minutes"
  - "If you can't make your interview, please ~~contact~~ [call] the number listed on your letter right away to reschedule."
  - "It will also ~~include information about how to request a hearing~~ [tell you what to do] if you disagree with our decision."

**Comparison State**
- [CalFresh](https://www.getcalfresh.org/en/apply) offers very accessible and streamlined language on its step-by-step page

**Comment by allyceh** [comment]
Made these content tweaks. Closing this issue.
