### ISSUE TITLE
Update modal to lower reading level of content

### ISSUE THREAD

**Issue by bestes-usds** [newjersey/dhs-oneapp#418]
**Screenshot of quick submit screen**
![Screen Shot 2020-11-23 at 3.20.24 PM.png](https://images.zenhubusercontent.com/5f579fdff369d2367fddffb6/812bb3e0-438b-4b40-8389-ced679d4ce48)

**Design principle**
- All content should be at a 5th grade reading level, which is readable and comprehensible for the greatest number of people

**Recommendation**
- Hemingway app reads text as 12th grade level. Replace with "If you're unable to finish this application, you can submit it now to establish your application date. A caseworker will get in touch with you later to fill in any missing information. We strongly urge you to finish the full application to get benefits sooner." (This new text is 8th grade level. @allyceh maybe you can work your magic to get this down lower)

**Hemingway screenshot**
![Screen Shot 2020-11-23 at 3.35.12 PM.png](https://images.zenhubusercontent.com/5f579fdff369d2367fddffb6/0da00187-0615-4e1b-91ca-e20d6ca0ac4b)

**Comment by allyceh** [comment]
@bestes-usds Tried to tweak further for plain language. Latest now reads: 
"If you're unable to finish this application, you can submit it now to establish your application date. A caseworker will get in touch with you later to collect any missing information. 

We strongly suggest that you finish the full application to get benefits sooner."

Still unsure about the concept of "establish your application date" and if this concept will jive with people. They might ask what this means and why they would want to establish their application date. 

Going to close this issue out and we can usability test with this updated lingo.
