### ISSUE TITLE
Update content on legal terms page to be less intimindating

### ISSUE THREAD

**Issue by bestes-usds** [newjersey/dhs-oneapp#420]
**Screenshot of quick submit screen**
![Screen Shot 2020-11-23 at 4.03.47 PM.png](https://images.zenhubusercontent.com/5f579fdff369d2367fddffb6/b597c0bc-a9a5-4f19-9f0f-ea1cdf1a200e)

**Design principle**
- Limit the use of legal language and bold warning text, which can be intimidating for users
- Instructions, messages, and alerts should be written in a warm and affirming voice. When explaining consequences or important procedures, be neutral in tone instead of dire and threatening

**Recommendation**
- The existing language is intimidating. We need to remove the ALL CAPS, cut down on the legalese, and soften the tone, while still complying with FNS regulations (below) 
- CalFresh offers a model worth considering: make people scroll to see the language about fraud and prosecution. They also use less legalese. (see below)

**FNS regulations**
- (i) In prominent and boldface lettering and understandable terms a statement that the information provided by the applicant in connection with the application for SNAP benefits will be subject to verification by Federal, State and local officials to determine if such information is factual; that if any information is incorrect, SNAP benefits may be denied to the applicant; and that the applicant may be subject to criminal prosecution for knowingly providing incorrect information;
- (ii) In prominent and boldface lettering and understandable terms a description of the civil and criminal provisions and penalties for violations of the Food and Nutrition Act of 2008;
- (iii) A statement to be signed by one adult household member which certifies, under penalty of perjury, the truth of the information contained in the application, including the information concerning citizenship and alien status of the members applying for benefits;

**Comparison State**
CalFresh Consent to Terms page:

Summary
- You have been honest on this application.
- You understand that GetCalFresh.org is a website run by Code for America, a non-profit organization that will submit your CalFresh application for you through www.mybenefitscalwin.org, www.c4yourself.com, or www.yourbenefits.laclrs.org (depending on where you live).
- You agree to the terms of the GetCalFresh privacy policy at www.getcalfresh.org/privacy
- Getting CalFresh will not affect your or your family’s immigration status. Immigration information is private and confidential.
- If you do not agree with these terms you can use other online applications found at www.benefitscal.org.
- You can learn about family planning services in the Family Planning brochure.
- You can register to vote online at www.registertovote.ca.gov or ask your CalFresh worker to help you register during your interview.

Details
I understand that by signing this application under penalty of perjury (making false statements), that:
- I read, or had read to me, the information in the official CF-285 CalFresh application and my answers to the questions in this application.
- My answers to the questions are true and complete to the best of my knowledge.
- I read, or had read to me, and I understand and agree to the Rights and Responsibilities for the CalFresh Program and the CalFresh Program Rules and Penalties.
- I understand that my county CalFresh office may verify the information in this application with Federal, State and local officials to determine if it is accurate.
- I understand that giving false or misleading statements or misrepresenting, hiding or withholding facts to establish eligibility for CalFresh is fraud. Fraud can cause a criminal case to be filed against me and/or I may be barred for a period of time (or life) from getting CalFresh benefits.

**Comment by bestes-usds** [comment]
Potential content for NJ:

Your responsibilities:
- I agree to the terms of NJ's [privacy policy] [add link].
- I may be asked to provide papers to verify the information I've provided in my application. 
- I agree that a county worker may verify the information in this application with Federal, State, and local officials to determine if it's accurate. They may also contact my employer, bank, or other parties to verify information.
- I'll have to tell my county of any changes to the information I provided on my application.
- I've been honest on this application. My answers are true and complete to the best of my knowledge. I understand that I can be held criminally responsible for lying on my application. I may also be barred for a period of time (or life) from getting benefits.
- I'll have to repay any benefits I should not have received, even if it's the county's error.
- I will use my benefits legally and will not sell, trade, or give away my benefits online or in person.
- I agree to cooperate with state or federal reviewers for an audit.
- I agree to release my information for program needs.

NJ's Responsibilities:
- I you think your county made a mistake, you can ask for a hearing.
- the NJ Department of Human Services and its county boards does not discriminate against any individual or group because of race, religion, age, national origin, marital status, sex, sexual orientation, gender identity or expression, political beliefs, or disability.


Other information:
- Getting benefits will not affect your or your family’s immigration status. Immigration information is private and confidential.
- You can register to vote online at [link] or ask your county worker to help you register during your interview.
- Applying for Medicaid is a separate process that can be completed at [link].


Sign Here:
Under penalties of perjury (making false statements), I state that I have reviewed this application, and to the best of my knowledge and belief, the answers I give within this application are true. I have listed all amounts and sources of income and property I receive/own, and the household and citizenship information I provided is accurate. If I am declaring an Authorized Representative, by signing below, I allow this person to sign my application and get official information about this application.

**Comment by bestes-usds** [comment]
Michigan's legal terms:
-----

Before you finish, read and agree to the legal terms.

### Things You Must Do
By signing the assistance application, you agree to do these things:

**Give Correct Information and Report Changes (All Programs)**

**Correct information.** You must give MDHHS correct and complete information about you and everyone in your household.

**If you give us incorrect or incomplete information on purpose, or you do not report a change,** you may be prosecuted for perjury or fraud, or denied benefits. (See "Penalties for Intentional Program Violation Or Fraud" for more information.)

**Reporting changes.** Tell your MDHHS specialist about changes or report changes online within 10 days of the change.*

*Exception: For FIP only, you must report a child leaving your home within 5 days of the date you know he or she will be absent for 30 days or more.

If you have any doubt about whether to report a change, contact your MDHHS specialist. Your MDHHS specialist will tell you if different reporting rules apply to you, such as simplified reporters.

The types of changes you must report are:
- Employment starts, stops (within 10 days of receiving your first/last payment) or changes.
- Change in rate of pay (within 10 days of receiving the first payment reflecting the change).
- Bank accounts (opening/changes/closures), sale/purchase of property, etc.
- Change of hours worked by more than five hours per week, if it will last more than one month.
- Unearned income starts or stops (like Social Security, unemployment or retirement benefits, etc.).
- Unearned income changes by more than: $50 per month for most programs, $25 per month for most MA programs.
- Change in assets.
- Change of address.
- Housing or utility cost stops, starts or changes.
- Anyone moving in or out of your home.
- Changes in child care need, cost or provider.
- Changes in child support amount paid out or received.
- Health or medical insurance premiums or change in coverage.
- Changes in a child’s school attendance.

If you file for bankruptcy, you shall send a copy of the official bankruptcy notice to : MDHHS Legal Services, P.O. Box 30037, Lansing, MI 48909

Additional Requirement for Health Care Coverage Only

You must tell the Michigan Department of Health and Human Services (MDHHS) if anything changes (and is different than) what you wrote on your reapplication. You can visit www.michigan.gov/mibridges or call your MDHHS specialist to report any changes. You understand that a change in your information could affect the eligibility for member(s) of your household.

Repay Extra Benefits (All Programs)

If you or anyone in your household receives benefits they are not eligible for, the adults in the household must repay the extra benefits. The benefits must be repaid even if there was no fraud. If MDHHS makes an error, the adults in the household must repay the extra benefits except in medical assistance cases.

For FAP, an authorized representative (someone with access to your food benefits who can shop for you) may also be responsible for repayment of any extra FAP benefits.

Recoupment. MDHHS may keep part of your future benefits as repayment for extra benefits you received.

Trafficking. FAP benefits that are sold or traded are treated as extra benefits and must be repaid.

Release of information. If you or anyone in your household received extra benefits, the information on your assistance application, including Social Security numbers, may be given to federal, state and private agencies to help with collection.

Provide Social Security numbers (Most Programs)

For most programs, under federal law 42 USC 1320b-7, you must provide Social Security numbers for everyone applying.

Exceptions include:
- When applying for child care only, you do not have to provide a Social Security number for adults or children who do not need child care.
- Non-citizens who cannot get a Social Security number may still qualify for medical assistance for emergency services, pregnancy and child birth. (See "Citizens and Non-Citizens.")
- When applying for FAP, you do not have to provide a social security number for anyone not applying.
- FAP clients are excused from providing and obtaining a Social Security number based on religious grounds.

MDHHS will help you apply for Social Security numbers. Give MDHHS the Social Security number as soon as you receive it. If you do not, your benefits may be reduced or denied. You may have to repay an overpayment.

MDHHS will use Social Security numbers to check whether you are eligible and receiving the correct benefits. MDHHS uses Social Security numbers to check information with other agencies. (See "Information About Your Household That Will Be Shared.")

Pursue Other Benefits (Most Programs)

You must apply for other benefits you may qualify for, such as:
- Unemployment benefits.
- Social Security and Supplemental Security Income (SSI) benefits.
- Veterans Administration benefits.

MDHHS will tell you if you need to apply for benefits.

If you do not pursue benefits when required, your MDHHS benefits may be reduced, closed or denied.

Immunize Children Under Age Six - Get Shots (Family Independence Program - FIP)

Children under age six must be immunized as recommended by the Michigan Department of Health and Human Services (MDHHS).

Your cash benefits may be reduced by $25 per month until your children are up-to-date on their immunizations.

A child is exempt from the immunization requirement if:
- (S)he is under two months of age.
- Immunizations are medically inappropriate for the child.
- Immunizations are against the family’s religious beliefs.
- Child Support Actions (Most Programs)

You will receive a letter about the child support program if:

- You receive FIP, FAP, MA or CDC; and
- One or more of the child’s parents do not live with the child.

Read and follow the directions in the letter. You will need to provide more information about yourself, the minor child(ren) in your home and the parents of the minor child(ren). The letter will tell you to complete an online form or to call OCS.

While you receive benefits from FIP, FAP, MA or CDC, you must keep working with the Office of Child Support, the Prosecuting Attorney and Friend of the Court to pursue paternity and/or support.

Good Cause. MDHHS will not require you to pursue paternity or support if you have good cause.

To claim good cause, tell your MDHHS specialist and ask for the "Claim of Good Cause" (DHS-2168) form. You may be asked to provide proof.

If you do not cooperate with child support actions when required, and do not have a good-cause reason, MDHHS will do all of the following for at least one month:

- Remove the food assistance benefits of the person not cooperating.
- Deny or stop your medical benefits for at least one month. We will not deny or stop Medicaid for children or pregnant women.
- Deny or stop your child care benefits.
- Deny or stop cash assistance for your entire household.
- Deny SER for failure to comply with a requirement of FIP.

When you get a FIP grant, you give (assign) to MDHHS any current support for you (spousal support) or minor children in your home (child support). This means when you get FIP, some of the spousal or child support you get from someone else may go to MDHHS to pay back some of the FIP grant.

You may get a child support payment that is owed to you while on FIP. If you do get a child support payment, call your local MDHHS office to find out if you can keep it. If your MDHHS specialist tells you the payment was sent to you in error, you must return the money. If you do not return the money, you may lose your FIP grant or your grant may be reduced.

If the amount of support MDHHS collects is more than your FIP grant for at least two months, MDHHS may close your FIP case so you can receive support payments directly.

If you get MA for your children, you give (assign) your rights to current and past medical support to the Michigan Department of Health and Human Services (MDHHS). This means when you get MA, medical support payments you get from someone else will go to MDHHS.

Follow Work Rules and Penalties (FIP or RCA and FAP)

Your work rules will depend on whether you receive FIP or RCA cash assistance, FAP benefits with no cash assistance, or time limited FAP benefits.

FIP or RCA cash assistance work rules. Your family must complete a Family Automated Screening Tool (FAST) and develop a Family Self-Sufficiency Plan (FSSP). The FAST and FSSP requirements are for FIP only. The FSSP will list the work activities that you must do up to 40 hours per week to receive FIP. You design this plan with your MDHHS specialist and the work participation program. For RCA only, you must develop a Refugee Family Self-Sufficiency Plan (RFSSP).

Complete the FAST (FIP only).
Help make and comply with a FSSP (FIP only) or RFSSP (RCA only).
Not quit, refuse work or reduce work hours.
Not get fired from a job due to misconduct or missing work.
Comply with assigned employment and/or self-sufficiency activities.

Penalties for breaking FIP or RCA work rules. If you break the FIP or RCA work rules without good cause (see "Good Cause"), MDHHS will:
Deny your application (you may reapply).
Stop FIP for your whole family for three months for the first time, six months for the second time and permanently for the third time.
Count all penalty months toward your state 48-month lifetime limit (FIP only).
Stop RCA for you for at least three months (but the rest of your household might be eligible).

If you receive both FIP and FAP, we may:
Stop or reduce your FAP benefits for at least one month if you are not excused from FAP work rules.
Count your FIP grant amount as income.

FAP work rules. All group members not meeting deferral criteria will be registered for work and may be required to perform specific work incuding cooperation with employment and training activities. (Note: If you receive both cash and food benefits, you must follow FIP work rules.)

If you are working, you may not:
Quit a job of 30 hours or more per week.
Voluntarily reduce work hours below 30 hours per week without good cause.
If you are not working, or you work less than 30 hours per week, you may not:
Refuse a job offer.
Refuse to participate in required employment-related activities that must be done to receive FAP.
Penalties for breaking FAP work rules. If you receive FAP and you break the work rules without good cause, your benefits will stop or be reduced for:
At least one month for the first time and
Six months for any other time after the first time

Time-limited food assistance rules. (NOTE: Time limits are not always in effect, so check with your MDHHS specialist.) Special time limits and work requirements might apply to you if you are:
A person without a disability.
At least 18 years old but under the age of 50, and
Living in a household with no children under age 18 (related or unrelated).

Work Rule Deferrals and Good Cause (FIP or RCA and FAP)

Work rule deferrals (excused). Some people who receive cash or food assistance may be excused from work rules. If you receive FIP and are excused from the work rules, you may have to do other activities. If you think you should be excused from work rules, talk to your MDHHS specialist.

NOTE: Reasons for being excused may change.

You may be excused from FIP or RCA work rules if you are:
Age 65 or older.
A parent of a baby less than 2 months old. You may be assigned to family strengthening activities once the baby is 6 weeks old.
Working 40 hours per week.
Caring for a child or spouse with a disability (depending on the person’s needs and the child’s school attendance).
A person with a disability or medical limitations.
Experiencing a domestic violence situation (determined by MDHHS).

You may be excused from FAP work rules if you are:
Age 60 or older.
Personally caring for a child under the age of 6 who is receiving FAP on your case.
Working 30 hours per week or earning at least minimum wage times 30 hours per week.
Attending high school, adult education, or a GED program at least half-time.
Injured, ill or personally caring for a household member with a disability.
Seven to nine months pregnant.
Pregnant with medical complications.
Applying for FAP at a Social Security office.
In substance abuse treatment or rehabilitation.
Applying for or receiving unemployment benefits.
Appealing the denial of unemployment benefits.

Good Cause. You have the right to claim good cause if you believe you should be excused from the FIP, RCA and/or FAP work rules. If you think you have a good cause reason, contact your MDHHS specialist right away.

NOTE: Reasons for good cause may change.

FIP or RCA or FAP - Reasons for good cause:

An unplanned event or factor that does not allow you to meet the work rules (For example, domestic violence, religion, health or safety risk or homelessness).
Illness or injury.
You requested child care that was not provided.
You requested transportation services that were not provided.
Long commute (more than two hours per day or more than three hours per day with child care).
You quit a job to take a comparable job.
Your job required you to commit illegal activities.
You are physically or mentally unable to do the job.
Your employer discriminated against you based on age, race, religion, national origin, color, height, weight, marital status, sex, sexual orientation, gender identity or expression, political beliefs or disability.
You are working 40 hours per week for at least the state minimum wage.
Reasonable accommodation was not provided.

FAP only - You may have a good cause reason if you / your:
Are deferred.
Moved due to another household member’s job or education/training.
Have a job that requires you to retire or to join, resign from, or refrain from joining a labor union or organization.
Have a job that is on strike or at a lockout site.
Have unreasonable work conditions.
Have been offered a job that is outside of your work experience during the first 30 days as a mandatory FAP work participant.
Employer is not able to keep the promise of work.

Important Things To Know

Penalties, Intentional Program Violation Or Fraud (FAP, FIP, SDA, CDC)

Welfare Fraud - Call 1-800-222-8558 to report suspected welfare fraud.

Intentional Program Violation (IPV) is when you make a false or misleading statement, hide, misrepresent or withhold facts on purpose to receive or continue to receive extra benefits.

Fraud/IPV - If we think you committed fraud/IPV, we may hold an administrative hearing, bring criminal charges or ask you to voluntarily sign a disqualification agreement.

FAP Trafficking - You may also be guilty of fraud/IPV if you trade, attempt to trade or sell your FAP benefits or Bridge card online or in person. You may not use or attempt to use FAP benefits or Bridge cards that belong to another household for your household. You may not use FAP benefits or Bridge cards to purchase or attempt to purchase anything other than food, seeds and plants to grow your own food for your household.

If it is proven in court that you are guilty of fraud:
You are subject to criminal penalties (for example, fines up to $250,000, jail/prison time up to 20 years, or both). You may be charged under other federal laws and a court may prevent you from receiving benefits for an additional 18 months; and
You must repay any extra benefits you received because of the fraud/IPV; and
You will be disqualified from receiving FIP/SDA and/or FAP benefits, see the table below.

If it is proven in an administrative hearing you are guilty of IPV, or you voluntarily sign a disqualification:
You will be disqualified from receiving FIP/SDA and/or FAP benefits, see the table below, and
You will have to repay the extra benefits you received because of the fraud or IPV.
CDC Program Penalties - Violation of program rules may result in a disqualification of 6 months, 12 months or a lifetime.

If you do any of the following:

You will lose FIP/SDA and/or FAP benefits for:

Make a false or misleading statement.
Hide, misrepresent or withhold facts to receive or continue to receive benefits.
Trade, attempt to trade, or sell less than $500 in FAP benefits or Bridge cards online or in person.
Use or attempt to use FAP or Cash benefits to buy ineligible items such as alcoholic drinks or tobacco.
Purchase beverages with FAP benefits then immediately empty the contents and return the container for the cash.
Use or attempt to use FAP benefits or Bridge cards that belong to someone else for your household.
One year for the first violation.
Two years for the second violation.
Life for the third violation.

If you are:

Found by a court or an administrative hearing to have lied about your identity or where you live to receive benefits on two or more cases at the same time.
You will lose FAP benefits for:

10 years
< >If you are:

Convicted in court of lying about your identity or where you live to receive benefits * in two or more cases at the same time.
*Benefits include programs funded under Title IV-A of the Social Security Act, Medicaid and Supplemental Security Income. This penalty will not stop you from receiving MA.

< >You will lose FIP benefits for:

10 years
If any member of the household is found guilty in court of:

Trading FAP benefits for drugs.
You will lose FAP benefits for:

Two years for the first offense.
Life for the second offense.
If any member of the household is found guilty in court of:

Trading or attempting to trade FAP benefits for firearms, ammunition or explosives.
Trading, buying or selling or attempting to trade, buy or sell FAP benefits of $500 or more for anything other than food online or in person.
Paying or attempting to pay for food purchased on credit with FAP.
You will lose FAP benefits for:

Life.

General Complaints

Clients have the right to make general complaints about matters other than the right to apply, non-discrimination or hearing issues. Written complaints can be sent to:

Michigan Department of Health and Human Services (MDHHS)

Specialization Action Center

235 S. Grand Avenue

P.O. Box 30037

Lansing, MI 48909

or they may call 1-855-275-6424 or 1-855-ASK-MICH

Hearing Rights

If you do not agree with a decision MDHHS makes to deny, reduce, or terminate benefits, or for failure to act with reasonable promptness, you have the right to request a hearing.

Food Assistance Program hearings may be requested by phone to your Specialist. Hearings for all other programs must be requested in writing. The request should include your name, address, and case number. Attach a copy of the notice, if possible. Go to www.michigan.gov/documents/FIA-Pub18_14356_7.pdf to download a form to use, or contact your specialist to request a form.

Mail the signed and dated request to the hearings coordinator at your local Department of Health and Human Services office.
Keep a copy of the request and any other document you attach for yourself.
At the hearing you can explain why you think the action is wrong and present evidence.
MDHHS must receive your request for appeal within 90 days of the mailing date of the notice or a hearing will not be granted.
MDHHS must receive your request for an appeal within 10 days of the mailing date of the notice to continue receiving your benefits.
You may be required to repay any assistance that you receive while your appeal is pending if: (1) the Department’s proposed action is upheld in the hearing decision, or (2) your request for appeal is withdrawn, or (3) you or your authorized representative do not attend this hearing.

You may choose anyone to represent you. If that person is not a lawyer or is not appointed by a court, you must give us your signed authorization and the person you wish to represent you must also sign the request. Attach a copy of the court’s order if the person is court-appointed to help you. The Michigan Administrative Hearing System will deny the request for an administrative hearing made by the representative if you do not provide proof of authorization.

If You Think We Discriminate

This institution is prohibited from discriminating on the basis of race, color, national origin, disability, age, sex and in some cases religion or political beliefs.

The U.S. Department of Agriculture also prohibits discrimination based on race, color, national origin, sex, religious creed, disability, age, political beliefs or reprisal or retaliation for prior civil rights activity in any program or activity conducted or funded by USDA.

Persons with disabilities who require alternative means of communication for program information (e.g. Braille, large print, audiotape, American Sign Language, etc.), should contact the Agency (State or local) where they applied for benefits. Individuals who are deaf, hard of hearing or have speech disabilities may contact USDA through the Federal Relay Service at 800-877-8339. Additionally, program information may be made available in languages other than English.

To file a program complaint of discrimination, complete the USDA Program Discrimination Complaint Form, (AD-3027), found online at: http://www.ascr.usda.gov/complaint_filing_cust.html, and at any USDA office, or write a letter addressed to USDA and provide in the letter all of the information requested in the form. To request a copy of the complaint form, call 866-632-9992. Submit your completed form or letter to USDA by:

(1) mail: U.S. Department of Agriculture

Office of the Assistant Secretary for Civil Rights

1400 Independence Avenue, SW

Washington, D.C. 20250-9410

(2) fax: 202-690-7442; or

(3) email: program.intake@usda.gov.

For any other information dealing with Supplemental Nutrition Assistance Program (SNAP) issues, persons should either contact the USDA SNAP Hotline Number at 800-221-5689, which is also in Spanish or call the State Information/Hotline Numbers (click the link for a listing of hotline numbers by State); found online at: http://www.fns.usda.gov/snap/contact_info/hotlines.htm.

To file a complaint of discrimination regarding a program receiving Federal financial assistance through the U.S. Department of Health and Human Services (HHS), write: HHS Director, Office for Civil Rights, Room 515-F, 200 Independence Avenue, S.W., Washington, D.C. 20201 or call 202-619-0403 (voice) or 800-537-7697 (TTY).

This institution is an equal opportunity provider.

Persons With Disabilities

You do not have to tell us about disabilities, but some help is only available to persons with disabilities. If you or someone in your household has a disability, we can make exceptions or give you special help.

Tell your MDHHS specialist if you need help.

If you do not tell us about a disability now, you can tell us about it later.

If you are denied special help or an exception you need because of a disability, and you think the denial was wrong, you may file a complaint of discrimination with:

USDA-see address in previous section.

You may file electronically via: http://www.michigan.gov/disabilityresources/

OR

This form may be printed and sent to:

MDHHS, Americans with Disabilities Act Coordinator

P.O. Box 30037, Suite 708

Lansing, MI 48909

(855) 275-6424

Citizens and Non-Citizens /Social Security Numbers

Social Security numbers and immigration papers are NOT required for a person who is:

Not applying for help.
An undocumented non-citizen only applying for medical assistance for emergency services, pregnancy or child birth.
Only applying for child care. (You must give a Social Security number for the child and the child must be a U.S. citizen or show immigration papers.)
Other eligible members of your household will still be able to receive help.

You may have to provide information about income and assets of all persons in your household, even if they are not applying.

Receiving food, medical, or emergency assistance will not affect your immigration status. If you are here illegally, it may affect your ability to stay in the U.S.

For some programs, persons claiming U.S. citizenship must provide proof of citizenship and identity. Acceptable proof of citizenship includes, but is not limited to, a U.S. passport, a certificate of naturalization, a U.S. public birth record showing birth in the U.S. or U.S. territories.

Persons receiving SSI, Social Security, Medicare, or adoption assistance; foster children, and newborn "safe delivery" babies are not required to provide proof of U.S. citizenship for MDHHS programs.

Race and Ethnicity

Answering questions about race and ethnicity is voluntary. If you do not answer these questions, your eligibility or benefit levels will not be affected.* The information is collected to ensure that program benefits are distributed without regard to race, color or national origin.

*If you choose not to answer these questions, your MDHHS specialist may choose an answer for you.

Domestic Violence

We may be able to waive some program requirements (such as working, looking for a job, pursuing child support or going to school) if participating would:

Put you or a family member in danger of physical or emotional harm.
Subject you to sexual abuse.
Otherwise be unfair to you.
You are authorized to receive domestic violence comprehensive services. Contact the MDHHS office in your area or your MDHHS specialist for more information or to access these services.

Resources:

Online at: www.michigan.gov/domesticviolence
DHS Publication 859, Is Someone Hurting You or Your Children? (also available in Spanish)
Online at: www.michigan.gov/dhs-publications
If You Receive Tribal Benefits

You cannot receive food benefits from the tribal food distribution program and the food assistance program at the same time.

You cannot receive tribal TANF (cash) from a tribe and FIP cash benefits from MDHHS at the same time.

Tribal organizations may receive LIHEAP funds from the federal government. Payments are limited to the highest amount available from either MDHHS or the tribal organization. MDHHS will ask you to prove any tribal LIHEAP payment you receive.

Bridge Card

Cash and/or food benefits are accessed by using a debit card. This debit card is called the Bridge card or Electronic Benefit Transfer (EBT) card.

Call EBT Customer Service toll-free at 1-888-678-8914 to:

Report a lost, stolen or damaged card.
Request a replacement card (after your first replacement card, your benefits may be reduced to cover the cost of replacing any additional cards).
Establish/change your personal ID number (PIN).
Find out your balance.
This same replacement card policy applies if you have one or both of the following individuals:

Someone who has access to your cash benefits (protective payee), or
For FAP, someone who you approved to purchase food for your household (authorized representative).
Repay Agreements

By signing the assistance application, you agree to do these things:

Recovery of Medical Costs (MA, AMP)

If any program run by the Michigan Department of Health and Human Services (MDHHS) pays the cost of hospital, surgical or medical services, you agree that the right to recover payments (from insurance, lawsuits, etc.) is transferred to the MDHHS. This includes payments from a third person or public or private contractor. Any recovery payment you receive must be paid to the State of Michigan, MDHHS.

Exception: Payments are not recovered from Medicare.

Medicaid Estate Recovery (MA -Long Term Care (LTC))

Upon the death of an individual, the Michigan Department of Health and Human Services (MDHHS) has the legal right to seek recovery from your estate for services paid by Medicaid (including Healthy Michigan Plan). MDHHS will not make a claim against the estate while there is a legal surviving spouse or a legal surviving child who is under the age of 21, blind or disabled.

An estate consists of real and personal property. Estate Recovery only applies to certain medicaid and Healthy Michigan Plan recipients who received Medicaid or Health Michigan Plan services after the implementation date of the program. MDHHS may agree not to pursue recovery if an undue hardship exists.

Lump Sums and Accumulated Benefits (SDA, State Funded FIP)

If you receive SDA, you agree to repay MDHHS if you receive:

Lump sum payments such as an inheritance, insurance settlement, etc., or
Accumulated benefits paid retroactively such as unemployment benefits or worker’s compensation.
If you receive SDA or state-funded FIP, you agree to repay MDHHS if you receive retroactive SSI.

You agree to allow Social Security Administration to pay MDHHS the amount of state-funded assistance you received while your SSI claim was pending.
If the first accumulated benefit payment is sent to you, you agree to pay MDHHS right away for the state-funded assistance you received while the claim was pending.
If you disagree with the amount MDHHS keeps, see "Hearing Rights."

Information About Your Household That Will Be Shared

By signing the assistance application, you agree that MDHHS can share information about you and your household with others, and that other agencies or people can give us information about you, as stated below:

Information MDHHS Will Get From Others

Social Security Administration information (all programs) - You agree that the Social Security Administration may give MDHHS all information needed to determine your eligibility.

Quality Control (QC) and/or Office of Inspector General (OIG) investigations - MDHHS might choose your case for a quality control review or a complete investigation.. If your case is chosen, MDHHS will contact you, other people, employers and/or agencies for proof of the information provided on your assistance application.

Law enforcement check (FAP, FIP, SER) - MDHHS may give or receive information from law enforcement officials for the purpose of catching persons fleeing to avoid the law.

Child care billing information (CDC) - Information submitted by your child care provider will be used in determining payment amounts.

Computer cross-checking (all programs)

- MDHHS will check with federal, state and private agencies to make sure the information you provide on the assistance application is correct. Verification of the information you provide may affect your household’s eligibility and level of benefits. MDHHS may check wages, income, assets, unemployment benefits, income tax refunds, Social Security benefits and numbers, child support, immigration status, etc.

If you give any information that does not match, MDHHS will check to find out what is correct. You may be asked for permission to contact employers, banks or other people.

MDHHS will check records from other states. You may be denied benefits in Michigan if you or other household members were disqualified in another state.

Information MDHHS Will Give To Others

Eligibility information (FAP) - MDHHS sends food assistance program (FAP) eligibility information to schools. This information allows your child(ren) to receive free or reduced-cost meals.

CDC - Notice will be sent to your child care provider when:

Your CDC has been approved and authorized.
Changes occur that impact your CDC eligibility.
Your CDC eligibility has ended.
Undocumented Aliens - MDHHS may send information about certain undocumented aliens to the Department of Homeland Security.

Survey Information - You may be contacted for survey information to help evaluate MDHHS quality of programs and customer service.

Coordination of Health Care

Coordination of health care programs and providers (MA) - The State’s medical assistance program relies on a large number of managed care health programs, mental health and substance abuse programs, and private providers to deliver quality care to persons like you.
To make sure you receive a high level of care and that your benefits are coordinated, providers in the program may share information about your care (or your child or ward) with other providers in the program when such information and consultation is clinically needed.
Information about you, your child or ward (MA) - Necessary information may be shared between Medicaid managed care health plans and programs in which you participate. Health plans, programs and providers that deliver health care to you may share necessary information in order to manage and coordinate health care and benefits. This information may include, when applicable, information relative to HIV, AIDS, AIDS-related complex (ARC) or other communicable diseases, information about behavioral or mental health services, and referral or treatment for alcohol and drug abuse as permitted by 42 CFR Part 2.
Web Site References

Career education and workforce programs: www.michigan.gov/mdcd
Child Development and Care Unlicensed Provider Application: www.michigan.gov/childcare
Earned Income Tax Credit: www.michiganeic.org
Energy Assistance Programs: www.michigan.gov/heatingassistance
Family Automated Screening Tool (FAST): www.michigan.gov/fast
Michigan Department of Health and Human Services (MDHHS): www.michigan.gov/mdhhs
Applying for Assistance: www.michigan.gov/dhs-applicationprocess
Cash Assistance: www.michigan.gov/dhs-cash
Emergency Services: www.michigan.gov/dhs-ser
Food Assistance: www.michigan.gov/foodstamps"
Medical Services: www.michigan.gov/dhs-medical
Child Support: www.michigan.gov/childsupport
Child Support Application and Case Information: www.michigan.gov/michildsupport
MDHHS County Offices: www.michigan.gov/dhs-countyoffices
MDHHS Forms and Applications: www.michigan.gov/dhs-forms
MDHHS Policy and Procedural Manuals: www.michigan.gov/dhs-manuals
Office of Services to the Aging: www.michigan.gov/osa
Women, Infants and Children (WIC) program: www.michigan.gov/wic
Michigan Disability Resources: www.michigan.gov/disabilityresources
Publications

Ask your MDHHS specialist if you would like any of these publications. The following publications are available online at: www.michigan.gov/dhs-publications. Some are also available in Spanish (Sp).

Child Support
Understanding Child Support: A Handbook for Parents (DHS-Pub-748) (Sp).
What Every Parent Should Know About Establishing Paternity (DHS-Pub-780) (Sp).
Fatherhood: Taking Responsibility for Your Child (DHS-Pub-806).
DNA Paternity Testing: Questions and Answers (DHS-Pub-865) (Sp).
Home Heating Credit- Notice to Potential Home Heating Credit Recipients (DHS-Pub-788) (Sp).
The following publications are available online at: www.michigan.gov/mdch. Select MDHHS Brochures Available for Download from the Quick Links.

Medicaid
Healthy Kids (MDCH Publication 655) - explains medical coverage for pregnant women, babies, and children.
Medicaid Fair Hearings: Rights and Responsibilities (MDCH Publication).
Your Rights and Responsibilities in a Health Plan (MDCH Publication 201).
Medicaid Deductible Information (MDCH Publication 617) - explains how your medical costs can be used to get your income at or below the income limits to be eligible for Medicaid.
Nursing Facility Eligibility (MDCH Publication 726) - explains eligibility for persons in or entering a nursing facility.
Medicare Savings Program: (MDCH Publication 769) - explains how to get help paying Medicare expenses.
Medicaid Fee for Service Handbook (MDCH Publication 669).
State Emergency Relief
You and Your Energy Bills (DHS-Pub-631).
MDHHS Can Help With Temporary Assistance (DHS-Pub-783).

**Comment by melissajschaff** [comment]
@allyceh @bestes-usds check out this pattern the UI team created or signing/agreeing to terms https://projects.invisionapp.com/share/YBZDF0N8ZEA#/screens/437230462

Thoughts?

**Comment by melissajschaff** [comment]
@bestes-usds @allyceh I'm going to run through designs this afternoon and make content updates

After sitting in on some of the NJ UI team's research sessions, I have an idea to change this page to make it a bit easier to explain. There was great feedback from the sessions, related to how well an applicant understands what they are agreeing to. They actually have a screen at the _start_ of the application flow that asks the applicant to agree to be honest and to initial. 

I'm going to sketch out some changes, similar to this concept for OneApp

**Comment by melissajschaff** [comment]
I recommend that OneApp follow a similar approach to the NJ UI prototype. The OneApp prototype will remain as originally designed for handoff and USDS proposes re-evaluation of the design based on the tested design from the USDS NJ UI team.
