### ISSUE TITLE
Add questions for Matt and Eddie to doc

### ISSUE THREAD

**Issue by allyceh** [newjersey/dhs-oneapp#451]
During our deep dive on Thursday, we'll have the opportunity to ask q's to Eddie and Matt. If there is anything that you want to know that I can share with them in advance, add it to [this doc](https://github.com/usds/covid-19/blob/master/new-jersey/safety-net-benefits/meeting-notes/questions%20for%20deep%20dive.md).

**Comment by ronaldheft-usds** [comment]
Got my questions added in.
