### ISSUE TITLE
Create confirmation page for Quick Submit

### ISSUE THREAD

**Issue by allyceh** [newjersey/dhs-oneapp#458]
Challenge: 
The current confirmation page in OneApp is generic, lacks complete information, and can better detail next steps to set applicant expectations. 

A few ideas, some of which are already captured in the prototype: 
- Transparency: tell applicants what is currently happening with their application, how it's being reviewed, and who is reviewing it. Give them some insight into how the process works so that they feel in control.
- Tell them how to track the status of their application and provide relevant links (currently in the prototype)
- Set expectations: communicate what is going to happen next (phone call? letter in the mail?) and when they should expect it. Tell them how the process is different for COVID, and when a casework might reach out to them.
  - How do they get benefits? What will they get in the mail? Are there any relevant links that can help them understand how to use their benefits so they are ready when the debit card arrives?
- Help them prepare: say if there is anything that the applicant can do to make the process seamless, like gather specific documents or upload them, and provide relevant links.
- Give them other helpful info: provide links to information or other NJ services that might be valuable to them. (currently, we have a link to a food bank. Is that the right place to send them, or are there other resources?)

Open questions: 
- How many confirmation page variations do we need for quick submit?
  - Does it make sense to draft one for expedited applicants, and one for non-expedited applicants?
    - How does the messaging differ?
- How does confirmation messaging differ if you are homeless versus have a permanent address?
  - Need to communicate how the caseworker will contact someone who is homeless so that they can be prepared

Design activities: 
- [x] Detail out all of the information requirements that need to be included in one confirmation page or in different variations of a confirmation page
  - @bestes-usds , can you start this?
- [ ] After we understand the info requirements, wordsmith to align with plain language guidelines, voice, and tone
- [ ] Update design accordingly

**Comment by allyceh** [comment]
@bestes-usds @melissajschaff Created a ticket to capture some of my thoughts on our confirmation page. Let me know what you think.

**Comment by bestes-usds** [comment]
@allyceh @melissajschaff apologies for the lengthy response:
There are no confirmation page requirements that I know about, beyond being required to provide a copy of the app. Best practice is to provide info on:
- Next steps
  - complete their interview
  - submit verifications 
  - eligibility determination and EBT(expedited)
- When and how they'll be contacted
- How long to wait before following up and how to follow up

I do think it's important to provide a link to a local food bank to help tie folks over while their apps are processed. These are also supplemental benefits and people are expected to cover some of their food costs. If including, we can ask NJ what external food bank locator they feel would be best. 

There are other resources we could link to, though I feel less strongly about them. Possible options are:
- additional info about SNAP/TANF/GA
- NJ resource page that summarizes other programs they might be eligible for (if this even exists)
- voter registration (in OneApp confirmation page)

I took a stab at draft text for regular vs. expedited vs. generic confirmation pages. They assume the applicant has a mailing address and do not account for [covid interview waivers](https://fns-prod.azureedge.net/sites/default/files/resource-files/SNAP-COVID19-AdjustInterviewRequirements.pdf). I'm not sure if any TANF/GA text is needed, but there's no info on the OneApp confirmation page that's specific to these programs.

We could potentially have homeless variants for each of these pages. Would need to add text encouraging them to visit their local office to get their mail so they don't miss their scheduled appt., verification request, and EBT card.

## Draft regular QS confirmation (post-covid, w/ mailing address)
Trigger: Answer "no" to all expedited screener questions

**Interview**
- Within the next 2 weeks, your county will reach out by phone or mail to set up an interview with you. The interview will take place over the phone or at the local office, and will last about X minutes (will be longer for QS). A worker will ask you about your household, income, expenses, and other information needed for your application. Calls from the county may come from a blocked/unlisted phone number (confirm with Alecia). 

- If you don't hear from your county in 2 weeks, we suggest contacting them about the status of your interview.

**Verifications**
- After your interview, your county will mail you a list of paperwork you'll need to submit to verify your eligibility. Commonly requested items are paystubs, rent/mortgage statements, and utility bills (check with Alecia about most common docs). You can submit paperwork online at [[link]](https://njdhs.powerappsportals.us/en-US/document-upload/). 

**Decision & App Status**
- Once the county has all the information they need, they'll send you a letter in the mail to let you know if you qualify. You can expect a decision within the next 30 days.

- You can [check your application status](https://oneapp.dhs.state.nj.us/Forms/ApplicationStatus.aspx) online at anytime (Ask Ron if only true for some counties right now?). If you have any questions or don't hear from your county, call [county phone number].

**Food bank**
- If you need immediate help with food, please visit your local food bank [link].

## Draft expedited QS confirmation (post-covid, w/ mailing address)
Trigger: Answer "yes" to at least one expedited screener question

**Interview**
- Within the next few days, your county will reach out by phone or mail to set up an interview with you. The interview will take place over the phone or at the local office, and will last about X minutes. A worker will ask you about your household, income, expenses, and other information needed for your application. Calls from the county may come from a blocked/unlisted phone number. 

- If you don't hear from your county within X days (2 or 3, ask Alecia), we suggest contacting them about the status of your interview.

**Decision & App Status**
[apps are temporarily certified while state waits for verifications]
- Your county will mail you a letter to let you know if you qualify. If approved, you'll receive a debit card with your benefits loaded onto it. If denied, the county will let you know why and tell you how to appeal their decision.
 
- You can [check your application status](https://oneapp.dhs.state.nj.us/Forms/ApplicationStatus.aspx) online at anytime. If you have any questions or don't hear from your county within a week, call [county phone number].

**Verifications**
[if verifications aren't provided, temporary certification is retracted]
- Your county will mail you a list of paperwork you'll need to submit to verify your eligibility and keep your benefits. Commonly requested items are paystubs, rent/mortgage statements, and utility bills. You can submit paperwork online at [[link]](https://njdhs.powerappsportals.us/en-US/document-upload/). 

**Food bank**
- If you need immediate help with food, please visit your local food bank [link].

## Draft generic QS confirmation (post-covid, w/ mailing address)
Trigger: Do not answer optional expedited screener

**Interview**
- Before you can get your benefits, your county will reach out by phone or mail to set up an interview with you. The interview will take place over the phone or at the local office, and will last about X minutes (will be longer for QS). A worker will ask you about your household, income, expenses, and other information needed for your application. Calls from the county may come from a blocked/unlisted phone number. 

**Verifications**
- After your interview, your county will mail you a list of paperwork you'll need to submit to verify your eligibility. Commonly requested items are paystubs, rent/mortgage statements, and utility bills. You can submit paperwork online at [[link]](https://njdhs.powerappsportals.us/en-US/document-upload/). 

**Decision & App Status**
- Your county will send you a letter in the mail to let you know if you qualify. You can [check your application status](https://oneapp.dhs.state.nj.us/Forms/ApplicationStatus.aspx) online at anytime. If you have any questions or don't hear from your county, call [county phone number].

**Food bank**
- If you need immediate help with food, please visit your local food bank [link].

**Comment by melissajschaff** [comment]
Some potential links sources:
- [About NJ services](https://njfc.force.com/njhelps/NJHelpsHomePage)
- [NJ Helps](https://njfc.force.com/njhelps)
- [NJ DHS pantries](https://www.nj211.org/resource-search/taxonomy/BD-1800.2000/_/1)

💡 If there isn't a specific link that NJ recommends for foodbank location, we could link to a Google Maps search, pre-populated with "food bank" and the county or zip code the applicant provided in their application

**Comment by allyceh** [comment]
My long overdue feedback: these variations look great, @bestes-usds. 

Here are a few suggestions once we flow one (or all, depending on how we want to proceed in staging) into the design @melissajschaff : 
- Currently, we have "Congratulations! You have successfully completed your application." on the confirmation page. Suggest taking a more modest rather than congratulatory tone. We could say something, like: 
"Your application was submitted. 

[County name] is reviewing your application submitted on [date]. Your confirmation number is [#]. Save your confirmation number to check the status of your application at any time."

**Comment by allyceh** [comment]
(Really minor) suggestions for places where we use hyphens @melissajschaff 

We should strive to avoid "\" for plain language. 

Interview section: 
Rather than, "Calls from the county may come from a blocked/unlisted phone number.", I propose saying "Calls from the county may come from a blocked number". 

Verification sectoin: 
Say "rent or mortgage" rather than using the \.

**Comment by melissajschaff** [comment]
added changes for "NO" responses to prototype.
