### ISSUE TITLE
need to determine branching of form

### ISSUE THREAD

**Issue by johnhashva** [newjersey/dhs-oneapp#5]
## Issue Description

- Applicant should have ability to select what they want to apply for (SNAP, GA, TANF)
- System should prompt if they are also eligible for GA and TANF and applicant did not select those programs
- Right now, system does not do any eligibility checks, so we need to determine if we want to do this
- Option A: Eligibility check, let applicant know, if yes, display the additional fields for the programs
- Option B: Use system as-is, so it's a false choice and applicant applies for all 3 even if they select only one

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by leahbannon2** [comment]
This might be something we tackle in the future, but it's not MVP right now.
