### ISSUE TITLE
Setup training plan for NJ OneApp developers

### ISSUE THREAD

**Issue by ronaldheft-gov** [newjersey/dhs-oneapp#64]
Set up a training plan that NJ developers can follow on their own time.

### Training Service

- [x] Reach out to Tom about NJ paying for training plan
- [x] (Tom) Get Treehouse approval from NJ training department
- [x] Reach out to Treehouse about teams pricing
- [x] (Blocked) Wait for Treehouse to send pricing
- [x] Pass Treehouse pricing on to NJ

### Course

- [x] Assemble a list of general developer courses (GitHub, etc)
- [x] Assemble a list of back-end courses
- [x] Assemble a list of front-end courses
- [x] Send course list over to Treehouse for them to make a track
- [x] Notify NJ developers about course list

### Dev Setup

- [x] Make sure all developers have access to GitHub

**Comment by Samara-Strauss** [comment]
@ronaldheft-usds to break this down into smaller tickets as needed.

Team has access to Treehouse now. Next Steps:

- List of courses to take
- Share list with NJ team

Mike is working on FE side of the courses.

Ron should be done with most of this today.

Yesterday, there was a larger convo for how training should go from here. Need ticket on how to proceed from here.

**Comment by ronaldheft-usds** [comment]
@mikepif Finished assembling a first pass on a list of course. Added back-end course and also some front-end course. List is available here:

https://github.com/newjersey/dhs-oneapp/blob/main/training/Treehouse_Recommended_Courses.md

Can you review and see if there are any additional courses you'd like to add? Once we have the list finalized, we can send over to Treehouse for them to create a custom track. Thanks!

**Comment by ronaldheft-usds** [comment]
@mikepif Checking in if you've had a change to review the list of courses.

**Comment by Samara-Strauss** [comment]
- Ron to send this over to Treehouse today.
- Once the course is made, we need to assign it to everyone in NJ in the Treehouse interface.

**Comment by Samara-Strauss** [comment]
Follow-up coming out of this ticket:

- Leah to follow up with Tom about joining Monday meetings and course list.

**Comment by ronaldheft-usds** [comment]
Custom track has been created and assigned.
